-- model_adapter_anthropic
-- Extracted verbatim from the historical packages/database/src/migrate.ts statement
-- stream (statements 7..7). Do not edit this file once it has been applied
-- anywhere: retiring schema requires a new migration containing the DROP.
--
-- Runs as its own committed transaction: 'anthropic' is referenced by a CHECK in 0008, and a new enum value cannot be used in the transaction that adds it.
-- @migrate transaction=false
ALTER TYPE model_adapter ADD VALUE IF NOT EXISTS 'anthropic';
