-- auth_identity_baseline
-- Extracted verbatim from the historical packages/database/src/migrate.ts statement
-- stream (statements 8..17). Do not edit this file once it has been applied
-- anywhere: retiring schema requires a new migration containing the DROP.
--
-- users, sessions, otp_challenges, registration_settings, invitations. users is the legacy-database sentinel.

CREATE TABLE IF NOT EXISTS users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),email text NOT NULL,role user_role NOT NULL DEFAULT 'user',status user_status NOT NULL DEFAULT 'active',session_version integer NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz,deletion_requested_at timestamptz);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_active_key ON users(lower(email)) WHERE deleted_at IS NULL;
CREATE TABLE IF NOT EXISTS sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES users(id),token_hash text NOT NULL UNIQUE,expires_at timestamptz NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),revoked_at timestamptz);
CREATE TABLE IF NOT EXISTS otp_challenges (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),email text NOT NULL,code_hash text NOT NULL,invitation_code_hash text,expires_at timestamptz NOT NULL,attempts integer NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),consumed_at timestamptz);
CREATE INDEX IF NOT EXISTS otp_email_idx ON otp_challenges(lower(email),created_at DESC);
CREATE TABLE IF NOT EXISTS registration_settings (singleton boolean PRIMARY KEY DEFAULT true CHECK(singleton),mode registration_mode NOT NULL DEFAULT 'open',updated_at timestamptz NOT NULL DEFAULT now(),updated_by uuid);
INSERT INTO registration_settings(singleton) VALUES(true) ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS invitations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),email text,code_hash text NOT NULL UNIQUE,expires_at timestamptz NOT NULL,created_by uuid NOT NULL REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),consumed_at timestamptz,revoked_at timestamptz);
ALTER TABLE invitations ALTER COLUMN email DROP NOT NULL;
ALTER TABLE invitations ADD COLUMN IF NOT EXISTS code_encrypted text;
