-- generation_core_baseline
-- Extracted verbatim from the historical packages/database/src/migrate.ts statement
-- stream (statements 18..25). Do not edit this file once it has been applied
-- anywhere: retiring schema requires a new migration containing the DROP.
--
-- model_configs, generation_jobs, assets, generation_outputs, outbox_events.

CREATE TABLE IF NOT EXISTS model_configs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),display_name text NOT NULL,adapter model_adapter NOT NULL,vendor_model_id text NOT NULL,sizes jsonb NOT NULL,quality_options jsonb NOT NULL DEFAULT '[]',max_count integer NOT NULL CHECK(max_count BETWEEN 1 AND 10),watermark boolean NOT NULL DEFAULT false,concurrency_limit integer NOT NULL CHECK(concurrency_limit > 0),enabled boolean NOT NULL DEFAULT false,sort_order integer NOT NULL DEFAULT 0,created_by uuid NOT NULL REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz);
CREATE TABLE IF NOT EXISTS generation_jobs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),created_by uuid NOT NULL REFERENCES users(id),model_id uuid NOT NULL REFERENCES model_configs(id),model_name text NOT NULL,adapter model_adapter NOT NULL,vendor_model_id text NOT NULL,prompt text,size text NOT NULL,quality text,count integer NOT NULL,watermark boolean NOT NULL DEFAULT false,status job_status NOT NULL DEFAULT 'queued',idempotency_key text NOT NULL,attempt integer NOT NULL DEFAULT 0,error_code text,provider_reference_id text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),started_at timestamptz,completed_at timestamptz,deleted_at timestamptz,UNIQUE(created_by,idempotency_key));
ALTER TABLE model_configs ADD COLUMN IF NOT EXISTS base_url text;
ALTER TABLE generation_jobs ADD COLUMN IF NOT EXISTS provider_base_url text;
CREATE INDEX IF NOT EXISTS jobs_owner_idx ON generation_jobs(created_by,created_at DESC) WHERE deleted_at IS NULL;
CREATE TABLE IF NOT EXISTS assets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),created_by uuid NOT NULL REFERENCES users(id),job_id uuid NOT NULL REFERENCES generation_jobs(id),prompt text,object_key text NOT NULL UNIQUE,mime_type text NOT NULL,width integer NOT NULL,height integer NOT NULL,size_bytes integer NOT NULL,checksum text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz);
CREATE TABLE IF NOT EXISTS generation_outputs (job_id uuid NOT NULL REFERENCES generation_jobs(id),asset_id uuid NOT NULL REFERENCES assets(id),PRIMARY KEY(job_id,asset_id));
CREATE TABLE IF NOT EXISTS outbox_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),event_type text NOT NULL,aggregate_id uuid NOT NULL,payload jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),dispatched_at timestamptz,attempts integer NOT NULL DEFAULT 0);
