-- provider_credentials_baseline
-- Extracted verbatim from the historical packages/database/src/migrate.ts statement
-- stream (statements 38..41). Do not edit this file once it has been applied
-- anywhere: retiring schema requires a new migration containing the DROP.
--
-- provider_credentials plus the model/job credential columns (generation_jobs deliberately has no FK).

CREATE TABLE IF NOT EXISTS provider_credentials (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),display_name text NOT NULL,adapter model_adapter NOT NULL,base_url text,api_key_encrypted text,api_key_fingerprint text,enabled boolean NOT NULL DEFAULT false,last_test_status text DEFAULT 'not_tested',last_test_error_code text,last_tested_at timestamptz,created_by uuid REFERENCES users(id),updated_by uuid REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz);
ALTER TABLE model_configs ADD COLUMN IF NOT EXISTS provider_credential_id uuid REFERENCES provider_credentials(id);
ALTER TABLE generation_jobs ADD COLUMN IF NOT EXISTS provider_credential_id uuid;
ALTER TABLE generation_jobs ADD COLUMN IF NOT EXISTS provider_credential_name text;
