-- model_configs_language
-- Extracted verbatim from the historical packages/database/src/migrate.ts statement
-- stream (statements 42..53). Do not edit this file once it has been applied
-- anywhere: retiring schema requires a new migration containing the DROP.
--
-- Language-model support in model_configs. Consumes the anthropic value added in 0002.

ALTER TABLE model_configs ADD COLUMN IF NOT EXISTS model_kind text NOT NULL DEFAULT 'image';
ALTER TABLE model_configs ADD COLUMN IF NOT EXISTS preset_id text;
ALTER TABLE model_configs ADD COLUMN IF NOT EXISTS language_protocol text;
ALTER TABLE model_configs ADD COLUMN IF NOT EXISTS max_output_tokens integer;
ALTER TABLE model_configs ADD COLUMN IF NOT EXISTS temperature numeric;
ALTER TABLE model_configs ADD COLUMN IF NOT EXISTS reasoning_effort text;
ALTER TABLE model_configs ALTER COLUMN sizes DROP NOT NULL;
ALTER TABLE model_configs ALTER COLUMN max_count DROP NOT NULL;
DO $$ BEGIN ALTER TABLE model_configs ADD CONSTRAINT model_configs_kind_check CHECK(model_kind IN ('image','language')); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE model_configs ADD CONSTRAINT model_configs_language_check CHECK(
  (model_kind='image' AND language_protocol IS NULL AND max_output_tokens IS NULL) OR
  (model_kind='language' AND language_protocol IN ('openai_chat','openai_responses','anthropic_messages') AND max_output_tokens > 0 AND sizes IS NULL AND max_count IS NULL)
); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE model_configs ADD CONSTRAINT model_configs_protocol_adapter_check CHECK(
  model_kind='image' OR
  (adapter='openai' AND language_protocol IN ('openai_chat','openai_responses')) OR
  (adapter='anthropic' AND language_protocol='anthropic_messages')
); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE model_configs ADD CONSTRAINT model_configs_reasoning_effort_check CHECK(reasoning_effort IS NULL OR reasoning_effort IN ('none','low','medium','high','xhigh')); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
