-- prompt_optimization_settings
-- Extracted verbatim from the historical packages/database/src/migrate.ts statement
-- stream (statements 54..61). Do not edit this file once it has been applied
-- anywhere: retiring schema requires a new migration containing the DROP.
--
-- Singleton settings plus the timeout constraint relaxation and preset size-list repairs.


CREATE TABLE IF NOT EXISTS prompt_optimization_settings (
  singleton boolean PRIMARY KEY DEFAULT true CHECK(singleton),
  enabled boolean NOT NULL DEFAULT false,
  allow_user_read_final_prompt boolean NOT NULL DEFAULT false,
  language_model_config_id uuid REFERENCES model_configs(id),
  timeout_ms integer NOT NULL DEFAULT 600000 CHECK(timeout_ms = 600000),
  updated_by uuid REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE prompt_optimization_settings DROP COLUMN IF EXISTS max_output_chars;
ALTER TABLE prompt_optimization_settings DROP CONSTRAINT IF EXISTS prompt_optimization_settings_timeout_ms_check;
INSERT INTO prompt_optimization_settings(singleton) VALUES(true) ON CONFLICT DO NOTHING;
UPDATE prompt_optimization_settings SET timeout_ms=600000,updated_at=now() WHERE singleton=true AND timeout_ms<>600000;
ALTER TABLE prompt_optimization_settings ADD CONSTRAINT prompt_optimization_settings_timeout_ms_check CHECK(timeout_ms = 600000);
UPDATE model_configs SET sizes='["1024x1024","1152x864","864x1152","1280x720","720x1280","1248x832","832x1248","1512x648","2048x2048","2304x1728","1728x2304","2848x1600","1600x2848","2496x1664","1664x2496","3136x1344","4096x4096","4704x3520","3520x4704","5504x3040","3040x5504","4992x3328","3328x4992","6240x2656"]'::jsonb,updated_at=now() WHERE preset_id='seedream-4-0' AND model_kind='image';
UPDATE model_configs SET sizes='["2048x2048","2304x1728","1728x2304","2848x1600","1600x2848","2496x1664","1664x2496","3136x1344","4096x4096","4704x3520","3520x4704","5504x3040","3040x5504","4992x3328","3328x4992","6240x2656"]'::jsonb,updated_at=now() WHERE preset_id='seedream-4-5' AND model_kind='image';
