-- prompt_optimizations
-- Extracted verbatim from the historical packages/database/src/migrate.ts statement
-- stream (statements 62..71). Do not edit this file once it has been applied
-- anywhere: retiring schema requires a new migration containing the DROP.
--
-- Per-job optimization rows and the generation_jobs columns that reference them.


CREATE TABLE IF NOT EXISTS prompt_optimizations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id uuid NOT NULL UNIQUE REFERENCES generation_jobs(id),
  created_by uuid NOT NULL REFERENCES users(id),
  status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','running','succeeded','failed')),
  input_prompt text NOT NULL,
  final_prompt text,
  input_language text NOT NULL DEFAULT 'und',
  template_name_snapshot text,
  template_description_snapshot text,
  template_path_snapshot text,
  template_instruction_snapshot text,
  template_content_sha256 text,
  language_model_config_id uuid REFERENCES model_configs(id),
  language_model_name_snapshot text NOT NULL,
  language_model_vendor_id_snapshot text NOT NULL,
  language_model_protocol_snapshot text NOT NULL,
  language_model_adapter_snapshot text NOT NULL,
  language_model_base_url_snapshot text,
  language_model_max_output_tokens_snapshot integer NOT NULL,
  language_model_temperature_snapshot numeric,
  language_model_reasoning_effort_snapshot text,
  optimizer_prompt_version text,
  provider_credential_id uuid REFERENCES provider_credentials(id),
  provider_credential_name_snapshot text,
  attempt integer NOT NULL DEFAULT 0,
  error_code text,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);
CREATE INDEX IF NOT EXISTS prompt_optimizations_owner_idx ON prompt_optimizations(created_by,created_at DESC) WHERE deleted_at IS NULL;
ALTER TABLE prompt_optimizations ADD COLUMN IF NOT EXISTS language_model_reasoning_effort_snapshot text;
ALTER TABLE prompt_optimizations ADD COLUMN IF NOT EXISTS optimizer_prompt_version text;
ALTER TABLE generation_jobs ADD COLUMN IF NOT EXISTS phase text;
ALTER TABLE generation_jobs ADD COLUMN IF NOT EXISTS optimization_mode text NOT NULL DEFAULT 'disabled';
ALTER TABLE generation_jobs ADD COLUMN IF NOT EXISTS prompt_optimization_id uuid REFERENCES prompt_optimizations(id);
ALTER TABLE generation_jobs ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE generation_jobs ADD COLUMN IF NOT EXISTS provider_error jsonb;
DO $$ BEGIN ALTER TABLE generation_jobs ADD CONSTRAINT generation_jobs_optimization_mode_check CHECK(optimization_mode IN ('disabled','enabled')); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
