-- generation_inputs_baseline
-- Extracted verbatim from the historical packages/database/src/migrate.ts statement
-- stream (statements 72..81). Do not edit this file once it has been applied
-- anywhere: retiring schema requires a new migration containing the DROP.
--
-- First-generation reference-image uploads and job input binding.


ALTER TABLE model_configs ADD COLUMN IF NOT EXISTS max_input_images integer NOT NULL DEFAULT 0;
DO $$ BEGIN ALTER TABLE model_configs ADD CONSTRAINT model_configs_max_input_images_check CHECK(max_input_images >= 0 AND max_input_images <= 4); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE model_configs ADD CONSTRAINT model_configs_language_input_images_check CHECK(model_kind='image' OR max_input_images = 0); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

UPDATE model_configs SET max_input_images=4,updated_at=now() WHERE preset_id IN ('openai-gpt-image-2','seedream-4-0','seedream-4-5') AND model_kind='image';

CREATE TABLE IF NOT EXISTS generation_input_images (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_by uuid NOT NULL REFERENCES users(id),
  status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','ready','attached','deleted')),
  object_key text NOT NULL UNIQUE,
  mime_type text NOT NULL,
  width integer,
  height integer,
  size_bytes integer NOT NULL,
  checksum text,
  attached_job_id uuid REFERENCES generation_jobs(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '24 hours'),
  object_deleted_at timestamptz,
  deleted_at timestamptz
);
CREATE INDEX IF NOT EXISTS generation_input_images_owner_idx ON generation_input_images(created_by,created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS generation_input_images_ttl_idx ON generation_input_images(status,expires_at) WHERE status IN ('pending','ready') AND object_deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS generation_input_images_attached_job_idx ON generation_input_images(attached_job_id) WHERE attached_job_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS generation_job_inputs (
  job_id uuid NOT NULL REFERENCES generation_jobs(id),
  input_image_id uuid NOT NULL UNIQUE REFERENCES generation_input_images(id),
  position integer NOT NULL CHECK(position >= 0 AND position < 4),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY(job_id,position)
);
CREATE INDEX IF NOT EXISTS generation_job_inputs_job_idx ON generation_job_inputs(job_id,position);
