-- wave1_relax_and_plugin_columns
-- Extracted verbatim from the historical packages/database/src/migrate.ts statement
-- stream (statements 82..99). Do not edit this file once it has been applied
-- anywhere: retiring schema requires a new migration containing the DROP.
--
-- Wave 1: relax adapter/vendor identity constraints and add provider_id/plugin_id/plugin_version.


-- ============================================================================
-- UNIFIED MEDIA ARCHITECTURE EXPAND / BACKFILL (Wave 1)
-- ============================================================================

-- 1. Relax legacy constraints and enums across model_configs, provider_credentials, and generation_jobs
-- Relax adapter enum columns to allow NULL for models/credentials driven by generic provider_id / plugin_id
ALTER TABLE model_configs ALTER COLUMN adapter DROP NOT NULL;
ALTER TABLE provider_credentials ALTER COLUMN adapter DROP NOT NULL;
ALTER TABLE generation_jobs ALTER COLUMN adapter DROP NOT NULL;
ALTER TABLE generation_jobs ALTER COLUMN vendor_model_id DROP NOT NULL;

-- Add provider_id, plugin_id, plugin_version to model_configs
ALTER TABLE model_configs ADD COLUMN IF NOT EXISTS provider_id text;
ALTER TABLE model_configs ADD COLUMN IF NOT EXISTS plugin_id text;
ALTER TABLE model_configs ADD COLUMN IF NOT EXISTS plugin_version text NOT NULL DEFAULT '1.0.0';

-- Relax model_configs constraints to admit 'video'
ALTER TABLE model_configs DROP CONSTRAINT IF EXISTS model_configs_kind_check;
DO $$ BEGIN ALTER TABLE model_configs ADD CONSTRAINT model_configs_kind_check CHECK(model_kind IN ('image','video','language')); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE model_configs DROP CONSTRAINT IF EXISTS model_configs_language_input_images_check;
DO $$ BEGIN ALTER TABLE model_configs ADD CONSTRAINT model_configs_language_input_images_check CHECK(model_kind IN ('image','video') OR max_input_images = 0); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE model_configs DROP CONSTRAINT IF EXISTS model_configs_protocol_adapter_check;
DO $$ BEGIN ALTER TABLE model_configs ADD CONSTRAINT model_configs_protocol_adapter_check CHECK(
  model_kind IN ('image','video') OR
  (adapter='openai' AND language_protocol IN ('openai_chat','openai_responses')) OR
  (adapter='anthropic' AND language_protocol='anthropic_messages') OR
  (provider_id IS NOT NULL)
); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE model_configs DROP CONSTRAINT IF EXISTS model_configs_language_check;
DO $$ BEGIN ALTER TABLE model_configs ADD CONSTRAINT model_configs_language_check CHECK(
  (model_kind IN ('image','video') AND language_protocol IS NULL AND max_output_tokens IS NULL) OR
  (model_kind='language' AND (language_protocol IS NULL OR language_protocol IN ('openai_chat','openai_responses','anthropic_messages')) AND max_output_tokens > 0 AND sizes IS NULL AND max_count IS NULL)
); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Backfill model_configs provider_id and plugin_id
-- Note: seedream maps to provider_id 'volcengine' so Seedream (image) and Seedance (video) share credentials
UPDATE model_configs
SET provider_id = COALESCE(provider_id, CASE
      WHEN adapter = 'openai' THEN 'openai'
      WHEN adapter = 'seedream' THEN 'volcengine'
      WHEN adapter = 'anthropic' THEN 'anthropic'
      ELSE adapter::text
    END),
    plugin_id = COALESCE(plugin_id, CASE
      WHEN model_kind = 'language' THEN CASE
        WHEN adapter = 'openai' THEN 'openai-language'
        WHEN adapter = 'anthropic' THEN 'anthropic-language'
        ELSE concat(adapter::text, '-language')
      END
      WHEN model_kind = 'video' THEN CASE
        WHEN adapter = 'seedream' THEN 'seedance-video'
        ELSE concat(adapter::text, '-video')
      END
      ELSE CASE
        WHEN adapter = 'openai' THEN 'openai-image'
        WHEN adapter = 'seedream' THEN 'seedream-image'
        ELSE concat(adapter::text, '-image')
      END
    END),
    plugin_version = COALESCE(plugin_version, '1.0.0')
WHERE provider_id IS NULL OR plugin_id IS NULL;

CREATE INDEX IF NOT EXISTS model_configs_provider_idx ON model_configs(provider_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS model_configs_plugin_idx ON model_configs(plugin_id, plugin_version) WHERE deleted_at IS NULL;
