-- wave1_provider_credentials_payload
-- Extracted verbatim from the historical packages/database/src/migrate.ts statement
-- stream (statements 100..107). Do not edit this file once it has been applied
-- anywhere: retiring schema requires a new migration containing the DROP.
--
-- Wave 1: structured credential payloads over the legacy single api key column.


-- 2. Expand provider_credentials: provider_id, schema_id, schema_version, payload_encrypted, encryption_key_id, configured_fields
ALTER TABLE provider_credentials ADD COLUMN IF NOT EXISTS provider_id text;
ALTER TABLE provider_credentials ADD COLUMN IF NOT EXISTS schema_id text;
ALTER TABLE provider_credentials ADD COLUMN IF NOT EXISTS schema_version integer NOT NULL DEFAULT 1;
ALTER TABLE provider_credentials ADD COLUMN IF NOT EXISTS payload_encrypted text;
ALTER TABLE provider_credentials ADD COLUMN IF NOT EXISTS encryption_key_id text;
ALTER TABLE provider_credentials ADD COLUMN IF NOT EXISTS configured_fields jsonb NOT NULL DEFAULT '{}';

-- Backfill provider_credentials:
-- seedream maps provider_id to 'volcengine'.
-- schema_id is explicitly set to 'legacy-api-key-v1' so the decoder knows this is an encrypted legacy string, not JSON.
UPDATE provider_credentials
SET provider_id = COALESCE(provider_id, CASE
      WHEN adapter = 'seedream' THEN 'volcengine'
      WHEN adapter = 'openai' THEN 'openai'
      WHEN adapter = 'anthropic' THEN 'anthropic'
      ELSE adapter::text
    END),
    schema_id = COALESCE(schema_id, 'legacy-api-key-v1'),
    schema_version = COALESCE(schema_version, 1),
    payload_encrypted = COALESCE(payload_encrypted, api_key_encrypted),
    configured_fields = CASE
      WHEN configured_fields = '{}'::jsonb OR configured_fields IS NULL THEN
        jsonb_strip_nulls(jsonb_build_object(
          'hasApiKey', api_key_encrypted IS NOT NULL,
          'apiKeyFingerprint', api_key_fingerprint,
          'baseUrl', base_url,
          'legacyFormat', true
        ))
      ELSE configured_fields
    END
WHERE provider_id IS NULL OR payload_encrypted IS NULL;

CREATE INDEX IF NOT EXISTS provider_credentials_provider_idx ON provider_credentials(provider_id) WHERE deleted_at IS NULL;
