-- wave1_model_config_revisions
-- Extracted verbatim from the historical packages/database/src/migrate.ts statement
-- stream (statements 108..114). Do not edit this file once it has been applied
-- anywhere: retiring schema requires a new migration containing the DROP.
--
-- Wave 1: immutable model config revisions, seeded by a PL/pgSQL cursor over existing models.


-- 3. Immutable model_config_revisions
CREATE TABLE IF NOT EXISTS model_config_revisions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  model_id uuid NOT NULL REFERENCES model_configs(id),
  revision integer NOT NULL CHECK(revision >= 1),
  provider_id text NOT NULL,
  plugin_id text NOT NULL,
  plugin_version text NOT NULL DEFAULT '1.0.0',
  vendor_model_id text,
  base_url text,
  credential_id uuid REFERENCES provider_credentials(id),
  credential_schema_version integer,
  capabilities jsonb NOT NULL DEFAULT '{}',
  normalized_config jsonb NOT NULL DEFAULT '{}',
  defaults jsonb NOT NULL DEFAULT '{}',
  snapshot_digest text NOT NULL,
  created_by uuid REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(model_id, revision)
);
CREATE INDEX IF NOT EXISTS model_config_revisions_model_idx ON model_config_revisions(model_id, revision DESC);
CREATE INDEX IF NOT EXISTS model_config_revisions_provider_idx ON model_config_revisions(provider_id);
CREATE INDEX IF NOT EXISTS model_config_revisions_plugin_idx ON model_config_revisions(plugin_id, plugin_version);
CREATE INDEX IF NOT EXISTS model_config_revisions_digest_idx ON model_config_revisions(snapshot_digest);

-- Add latest_revision_id linkage to model_configs
ALTER TABLE model_configs ADD COLUMN IF NOT EXISTS latest_revision_id uuid REFERENCES model_config_revisions(id);

-- Deterministic backfill of initial model_config_revisions for existing model_configs
DO $$
DECLARE
  rec RECORD;
  rev_id uuid;
  prov_id text;
  p_id text;
  cap jsonb;
  norm jsonb;
  dflt jsonb;
  dig text;
  cred_schema_ver integer;
BEGIN
  FOR rec IN SELECT m.*, pc.schema_version AS cred_schema_ver
             FROM model_configs m
             LEFT JOIN provider_credentials pc ON pc.id = m.provider_credential_id
             WHERE m.deleted_at IS NULL LOOP
    IF NOT EXISTS (SELECT 1 FROM model_config_revisions WHERE model_id = rec.id) THEN
      prov_id := COALESCE(rec.provider_id, CASE
        WHEN rec.adapter = 'seedream' THEN 'volcengine'
        WHEN rec.adapter = 'openai' THEN 'openai'
        WHEN rec.adapter = 'anthropic' THEN 'anthropic'
        ELSE rec.adapter::text
      END);

      p_id := COALESCE(rec.plugin_id, CASE
        WHEN rec.model_kind = 'language' THEN CASE
          WHEN rec.adapter = 'openai' THEN 'openai-language'
          WHEN rec.adapter = 'anthropic' THEN 'anthropic-language'
          ELSE concat(rec.adapter::text, '-language')
        END
        WHEN rec.model_kind = 'video' THEN CASE
          WHEN rec.adapter = 'seedream' THEN 'seedance-video'
          ELSE concat(rec.adapter::text, '-video')
        END
        ELSE CASE
          WHEN rec.adapter = 'openai' THEN 'openai-image'
          WHEN rec.adapter = 'seedream' THEN 'seedream-image'
          ELSE concat(rec.adapter::text, '-image')
        END
      END);

      cap := jsonb_build_object(
        'mediaKind', rec.model_kind,
        'modes', CASE
          WHEN rec.model_kind = 'video' THEN jsonb_build_array('text_to_video', 'image_to_video')
          WHEN rec.model_kind = 'image' THEN jsonb_build_array('text_to_image', 'image_to_image')
          ELSE jsonb_build_array()
        END,
        'sizes', COALESCE(rec.sizes, '[]'::jsonb),
        'qualityOptions', COALESCE(rec.quality_options, '[]'::jsonb),
        'maxCount', COALESCE(rec.max_count, 1),
        'maxInputImages', COALESCE(rec.max_input_images, 0)
      );

      norm := jsonb_strip_nulls(jsonb_build_object(
        'vendorModelId', rec.vendor_model_id,
        'baseUrl', rec.base_url,
        'concurrencyLimit', rec.concurrency_limit,
        'watermark', rec.watermark,
        'sortOrder', rec.sort_order,
        'modelKind', rec.model_kind,
        'languageProtocol', rec.language_protocol,
        'maxOutputTokens', rec.max_output_tokens,
        'temperature', rec.temperature,
        'reasoningEffort', rec.reasoning_effort
      ));

      dflt := jsonb_strip_nulls(jsonb_build_object(
        'vendorModelId', rec.vendor_model_id,
        'watermark', rec.watermark,
        'concurrencyLimit', rec.concurrency_limit
      ));

      cred_schema_ver := COALESCE(rec.cred_schema_ver, 1);

      dig := encode(digest(concat(rec.id::text, ':', prov_id, ':', p_id, ':', COALESCE(rec.vendor_model_id, ''), ':', cap::text), 'sha256'), 'hex');

      INSERT INTO model_config_revisions(
        model_id, revision, provider_id, plugin_id, plugin_version,
        vendor_model_id, base_url, credential_id, credential_schema_version,
        capabilities, normalized_config, defaults, snapshot_digest, created_by, created_at
      ) VALUES (
        rec.id, 1, prov_id, p_id, '1.0.0',
        rec.vendor_model_id, rec.base_url, rec.provider_credential_id, cred_schema_ver,
        cap, norm, dflt, dig, rec.created_by, rec.created_at
      )
      RETURNING id INTO rev_id;

      UPDATE model_configs SET latest_revision_id = rev_id WHERE id = rec.id;
    END IF;
  END LOOP;
END $$;
