-- wave1_generation_jobs_expand
-- Extracted verbatim from the historical packages/database/src/migrate.ts statement
-- stream (statements 115..133). Do not edit this file once it has been applied
-- anywhere: retiring schema requires a new migration containing the DROP.
--
-- Wave 1: media kind, progress, cancellation and the normalized request digest on generation_jobs.


-- 4. Expand generation_jobs and relax image-only required constraints
ALTER TABLE generation_jobs ADD COLUMN IF NOT EXISTS media_kind text NOT NULL DEFAULT 'image';
ALTER TABLE generation_jobs ADD COLUMN IF NOT EXISTS model_revision_id uuid REFERENCES model_config_revisions(id);
ALTER TABLE generation_jobs ADD COLUMN IF NOT EXISTS provider_id text;
ALTER TABLE generation_jobs ADD COLUMN IF NOT EXISTS plugin_id text;
ALTER TABLE generation_jobs ADD COLUMN IF NOT EXISTS plugin_version text;
ALTER TABLE generation_jobs ADD COLUMN IF NOT EXISTS normalized_request jsonb;
ALTER TABLE generation_jobs ADD COLUMN IF NOT EXISTS request_digest text;
ALTER TABLE generation_jobs ADD COLUMN IF NOT EXISTS progress integer NOT NULL DEFAULT 0 CHECK(progress >= 0 AND progress <= 100);
ALTER TABLE generation_jobs ADD COLUMN IF NOT EXISTS cancel_requested_at timestamptz;

-- Relax image-only required columns (size, count) for future video jobs
ALTER TABLE generation_jobs ALTER COLUMN size DROP NOT NULL;
ALTER TABLE generation_jobs ALTER COLUMN count DROP NOT NULL;

DO $$ BEGIN ALTER TABLE generation_jobs ADD CONSTRAINT generation_jobs_media_kind_check CHECK(media_kind IN ('image','video')); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE generation_jobs ADD CONSTRAINT generation_jobs_image_requirements_check CHECK(
  media_kind <> 'image' OR (size IS NOT NULL AND count IS NOT NULL)
); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Uniqueness / index for request digest
CREATE INDEX IF NOT EXISTS generation_jobs_request_digest_idx ON generation_jobs(created_by, request_digest) WHERE request_digest IS NOT NULL AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS generation_jobs_provider_idx ON generation_jobs(provider_id) WHERE provider_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS generation_jobs_plugin_idx ON generation_jobs(plugin_id, plugin_version) WHERE plugin_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS generation_jobs_status_phase_idx ON generation_jobs(status, phase) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS generation_jobs_cancel_requested_idx ON generation_jobs(cancel_requested_at) WHERE cancel_requested_at IS NOT NULL AND status IN ('queued','running');

-- Backfill existing generation_jobs
UPDATE generation_jobs
SET provider_id = COALESCE(provider_id, CASE
      WHEN adapter = 'openai' THEN 'openai'
      WHEN adapter = 'seedream' THEN 'volcengine'
      ELSE adapter::text
    END),
    plugin_id = COALESCE(plugin_id, CASE
      WHEN adapter = 'openai' THEN 'openai-image'
      WHEN adapter = 'seedream' THEN 'seedream-image'
      ELSE concat(adapter::text, '-image')
    END),
    plugin_version = COALESCE(plugin_version, '1.0.0'),
    media_kind = COALESCE(media_kind, 'image'),
    normalized_request = CASE
      WHEN normalized_request IS NULL THEN
        jsonb_strip_nulls(jsonb_build_object(
          'modelId', model_id,
          'prompt', prompt,
          'parameters', jsonb_strip_nulls(jsonb_build_object(
            'size', size,
            'quality', quality,
            'count', count,
            'watermark', watermark
          ))
        ))
      ELSE normalized_request
    END,
    request_digest = COALESCE(request_digest, encode(digest(concat(model_id::text, ':', COALESCE(prompt, ''), ':', COALESCE(size, ''), ':', COALESCE(count::text, '1')), 'sha256'), 'hex'))
WHERE plugin_id IS NULL OR request_digest IS NULL;
