-- wave1_media_uploads
-- Extracted verbatim from the historical packages/database/src/migrate.ts statement
-- stream (statements 134..152). Do not edit this file once it has been applied
-- anywhere: retiring schema requires a new migration containing the DROP.
--
-- Wave 1: generic media_uploads superseding generation_input_images, with role and position linkage.


-- 5. Generic media_uploads and generation_job_inputs role / position linkage
CREATE TABLE IF NOT EXISTS media_uploads (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_by uuid NOT NULL REFERENCES users(id),
  media_kind text NOT NULL DEFAULT 'image' CHECK(media_kind IN ('image','video')),
  status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','ready','attached','deleted')),
  object_key text NOT NULL UNIQUE,
  mime_type text NOT NULL,
  width integer,
  height integer,
  duration_seconds numeric,
  fps numeric,
  size_bytes integer NOT NULL,
  checksum text,
  attached_job_id uuid REFERENCES generation_jobs(id),
  metadata jsonb NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '24 hours'),
  object_deleted_at timestamptz,
  deleted_at timestamptz
);
CREATE INDEX IF NOT EXISTS media_uploads_owner_idx ON media_uploads(created_by, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS media_uploads_ttl_idx ON media_uploads(status, expires_at) WHERE status IN ('pending','ready') AND object_deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS media_uploads_attached_job_idx ON media_uploads(attached_job_id) WHERE attached_job_id IS NOT NULL;

-- Expand generation_input_images with media_kind for compatibility
ALTER TABLE generation_input_images ADD COLUMN IF NOT EXISTS media_kind text NOT NULL DEFAULT 'image';

-- Expand generation_job_inputs to support generic upload_id and role
ALTER TABLE generation_job_inputs ADD COLUMN IF NOT EXISTS upload_id uuid REFERENCES media_uploads(id);
ALTER TABLE generation_job_inputs ADD COLUMN IF NOT EXISTS role text NOT NULL DEFAULT 'prompt_image';
DO $$ BEGIN ALTER TABLE generation_job_inputs ADD CONSTRAINT generation_job_inputs_role_check CHECK(role IN ('prompt_image','reference_image','first_frame','last_frame','source_video')); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER TABLE generation_job_inputs ALTER COLUMN input_image_id DROP NOT NULL;

-- Widen the role list for 局部框选修改: 'mask' carries the alpha PNG that marks
-- the region an edit may regenerate. ADD CONSTRAINT alone can never change an
-- already-installed check, so drop first — same pattern as the position
-- constraint relaxation below.
ALTER TABLE generation_job_inputs DROP CONSTRAINT IF EXISTS generation_job_inputs_role_check;
DO $$ BEGIN ALTER TABLE generation_job_inputs ADD CONSTRAINT generation_job_inputs_role_check CHECK(role IN ('prompt_image','reference_image','first_frame','last_frame','source_video','mask')); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Relax position constraint from < 4 to >= 0 for extensible multi-slot inputs (e.g. video / multi-frame)
ALTER TABLE generation_job_inputs DROP CONSTRAINT IF EXISTS generation_job_inputs_position_check;
DO $$ BEGIN ALTER TABLE generation_job_inputs ADD CONSTRAINT generation_job_inputs_position_check CHECK(position >= 0 AND position < 32); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Deterministic backfill from generation_input_images into media_uploads
INSERT INTO media_uploads(id, created_by, media_kind, status, object_key, mime_type, width, height, size_bytes, checksum, attached_job_id, created_at, updated_at, expires_at, object_deleted_at, deleted_at)
SELECT id, created_by, 'image', status, object_key, mime_type, width, height, size_bytes, checksum, attached_job_id, created_at, updated_at, expires_at, object_deleted_at, deleted_at
FROM generation_input_images
ON CONFLICT (id) DO NOTHING;

-- Backfill generation_job_inputs upload_id from input_image_id
UPDATE generation_job_inputs
SET upload_id = input_image_id
WHERE upload_id IS NULL AND input_image_id IS NOT NULL;

-- Enforce uniqueness on generation_job_inputs(upload_id) where upload_id is present
CREATE UNIQUE INDEX IF NOT EXISTS generation_job_inputs_upload_id_unique ON generation_job_inputs(upload_id) WHERE upload_id IS NOT NULL;

-- An input can also *reference* an existing gallery image instead of an upload, so
-- reusing one's own earlier output never copies bytes. No upload row is created for
-- these, which is what keeps the upload TTL sweep and DELETE /generation-uploads
-- from ever reaching a gallery object.
ALTER TABLE generation_job_inputs ADD COLUMN IF NOT EXISTS asset_id uuid REFERENCES assets(id);
-- One-sided exclusion, not XOR: rows written before the upload_id backfill above have
-- both columns NULL, and ADD CONSTRAINT validates the whole table right now.
DO $$ BEGIN ALTER TABLE generation_job_inputs ADD CONSTRAINT generation_job_inputs_upload_or_asset_check CHECK(NOT (upload_id IS NOT NULL AND asset_id IS NOT NULL)); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
-- Deliberately non-unique: the same gallery image may feed any number of later jobs.
CREATE INDEX IF NOT EXISTS generation_job_inputs_asset_idx ON generation_job_inputs(asset_id) WHERE asset_id IS NOT NULL;
