-- wave1_provider_runs
-- Extracted verbatim from the historical packages/database/src/migrate.ts statement
-- stream (statements 153..158). Do not edit this file once it has been applied
-- anywhere: retiring schema requires a new migration containing the DROP.
--
-- Wave 1: provider_runs operation state machine, capacity reservation and worker leases.


-- 6. provider_runs table:
-- operation_state includes: 'submitting','submission_unknown','waiting','importing','canceling','succeeded','failed','canceled'
-- supports provider_accepted_at, capacity reservation lifecycle vs worker lease, encrypted serialized operation/output state
CREATE TABLE IF NOT EXISTS provider_runs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id uuid NOT NULL REFERENCES generation_jobs(id),
  attempt integer NOT NULL DEFAULT 1 CHECK(attempt >= 1),
  provider_id text NOT NULL DEFAULT 'legacy',
  plugin_id text NOT NULL,
  plugin_version text NOT NULL DEFAULT '1.0.0',
  operation_state text NOT NULL DEFAULT 'submitting' CHECK(operation_state IN ('submitting','submission_unknown','waiting','importing','canceling','succeeded','failed','canceled')),
  client_token text NOT NULL,
  remote_id text,
  state_revision integer NOT NULL DEFAULT 1 CHECK(state_revision >= 1),
  next_action_at timestamptz,
  -- Capacity reservation lifecycle: pending | reserved | released
  capacity_state text NOT NULL DEFAULT 'pending' CHECK(capacity_state IN ('pending','reserved','released')),
  capacity_reservation_id text,
  capacity_reserved_at timestamptz,
  capacity_released_at timestamptz,
  -- Worker execution lease lifecycle
  worker_lease_token text,
  worker_lease_expires_at timestamptz,
  -- Serialized operation state (untrusted / encrypted envelope to prevent raw signed URL leaks)
  encrypted_state_payload text,
  encrypted_state_key_id text,
  -- Manifest metadata (descriptive manifest without signed URLs)
  output_manifest jsonb,
  error jsonb,
  submitted_at timestamptz,
  provider_accepted_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(job_id, attempt),
  UNIQUE(client_token)
);
CREATE INDEX IF NOT EXISTS provider_runs_active_idx ON provider_runs(operation_state, next_action_at) WHERE operation_state IN ('submitting','submission_unknown','waiting','importing','canceling');
CREATE INDEX IF NOT EXISTS provider_runs_lease_idx ON provider_runs(worker_lease_token, worker_lease_expires_at) WHERE worker_lease_token IS NOT NULL;
CREATE INDEX IF NOT EXISTS provider_runs_remote_idx ON provider_runs(plugin_id, remote_id) WHERE remote_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS provider_runs_job_idx ON provider_runs(job_id, attempt DESC);
CREATE INDEX IF NOT EXISTS provider_runs_capacity_active_idx ON provider_runs(provider_id, plugin_id) WHERE capacity_state = 'reserved' AND operation_state NOT IN ('succeeded','failed','canceled');
