-- wave1_output_ingestions
-- Extracted verbatim from the historical packages/database/src/migrate.ts statement
-- stream (statements 159..161). Do not edit this file once it has been applied
-- anywhere: retiring schema requires a new migration containing the DROP.
--
-- Wave 1: crash-safe per-output ingestion ledger.


-- 7. Deterministic output-ingestion table with run/output identity, object key, multipart upload id, checksum/bytes/attached timestamps
-- Remote outputs are located securely via encrypted provider_runs state and referenced by (run_id, output_index)
CREATE TABLE IF NOT EXISTS output_ingestions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id uuid NOT NULL REFERENCES generation_jobs(id),
  run_id uuid NOT NULL REFERENCES provider_runs(id),
  output_index integer NOT NULL DEFAULT 0 CHECK(output_index >= 0),
  media_kind text NOT NULL DEFAULT 'image' CHECK(media_kind IN ('image','video')),
  storage_object_key text NOT NULL UNIQUE,
  multipart_upload_id text,
  checksum text,
  size_bytes bigint,
  mime_type text,
  ingestion_state text NOT NULL DEFAULT 'pending' CHECK(ingestion_state IN ('pending','downloading','uploading','verifying','persisted','failed')),
  asset_id uuid REFERENCES assets(id),
  metadata jsonb NOT NULL DEFAULT '{}',
  error jsonb,
  download_started_at timestamptz,
  download_completed_at timestamptz,
  attached_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(run_id, output_index)
);
CREATE INDEX IF NOT EXISTS output_ingestions_job_idx ON output_ingestions(job_id, output_index);
CREATE INDEX IF NOT EXISTS output_ingestions_state_idx ON output_ingestions(ingestion_state) WHERE ingestion_state NOT IN ('persisted','failed');
