-- wave1_assets_media
-- Extracted verbatim from the historical packages/database/src/migrate.ts statement
-- stream (statements 162..174). Do not edit this file once it has been applied
-- anywhere: retiring schema requires a new migration containing the DROP.
--
-- Wave 1: video metadata and poster columns on assets.


-- 8. assets media_kind plus video metadata (duration, fps, codec, audio, poster)
-- Relax width and height NOT NULL constraints for video metadata unknown at ingest
ALTER TABLE assets ALTER COLUMN width DROP NOT NULL;
ALTER TABLE assets ALTER COLUMN height DROP NOT NULL;

ALTER TABLE assets ADD COLUMN IF NOT EXISTS media_kind text NOT NULL DEFAULT 'image';
ALTER TABLE assets ADD COLUMN IF NOT EXISTS duration_seconds numeric;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS fps numeric;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS codec text;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS has_audio boolean;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS poster_asset_id uuid REFERENCES assets(id);
ALTER TABLE assets ADD COLUMN IF NOT EXISTS poster_object_key text;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS metadata jsonb NOT NULL DEFAULT '{}';

DO $$ BEGIN ALTER TABLE assets ADD CONSTRAINT assets_media_kind_check CHECK(media_kind IN ('image','video')); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE INDEX IF NOT EXISTS assets_media_kind_idx ON assets(media_kind, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS assets_poster_idx ON assets(poster_asset_id) WHERE poster_asset_id IS NOT NULL;
