-- outbox_dedupe_key
-- Extracted verbatim from the historical packages/database/src/migrate.ts statement
-- stream (statements 175..176). Do not edit this file once it has been applied
-- anywhere: retiring schema requires a new migration containing the DROP.
--
-- Wave 1: transactional outbox dedupe key.


-- 9. outbox_events dedupe key and index
ALTER TABLE outbox_events ADD COLUMN IF NOT EXISTS dedupe_key text;
CREATE UNIQUE INDEX IF NOT EXISTS outbox_events_dedupe_key_idx ON outbox_events(dedupe_key) WHERE dedupe_key IS NOT NULL;
