-- remove_billing_credits
-- Extracted verbatim from the historical packages/database/src/migrate.ts statement
-- stream (statements 206..214). Do not edit this file once it has been applied
-- anywhere: retiring schema requires a new migration containing the DROP.
--
-- Destructive: drops the billing tables and credit columns. Children before parents.


-- ============================================================================
-- REMOVE BILLING/CREDITS (destructive, idempotent; children before parents)
-- Generations run free; the credit ledger, charge state machine and pricing
-- metadata are fully retired. This drops historical data by design.
-- ============================================================================
DROP TABLE IF EXISTS generation_charges CASCADE;
DROP TABLE IF EXISTS credit_ledger CASCADE;
DROP TABLE IF EXISTS credit_accounts CASCADE;
DROP TABLE IF EXISTS billing_settings CASCADE;
DO $$ BEGIN ALTER TABLE prompt_optimization_settings DROP CONSTRAINT IF EXISTS prompt_optimization_credits_per_job_check; EXCEPTION WHEN undefined_table THEN NULL; END $$;
ALTER TABLE prompt_optimization_settings DROP COLUMN IF EXISTS credits_per_job;
DO $$ BEGIN ALTER TABLE model_configs DROP CONSTRAINT IF EXISTS model_configs_credits_per_image_check; EXCEPTION WHEN undefined_table THEN NULL; END $$;
ALTER TABLE model_configs DROP COLUMN IF EXISTS credits_per_image;
ALTER TABLE model_config_revisions DROP COLUMN IF EXISTS pricing;
