-- provider_plugins
-- Extracted verbatim from the historical packages/database/src/migrate.ts statement
-- stream (statements 215..220). Do not edit this file once it has been applied
-- anywhere: retiring schema requires a new migration containing the DROP.
--
-- Uploaded provider plugin packages and the model_configs plugin_source column.


-- ============================================================================
-- INSTALLED PROVIDER PLUGIN PACKAGES (plugin upload)
-- Admins upload self-contained provider plugin code packages (plugin_id@
-- plugin_version plus one .mjs artifact). The API validates the artifact and
-- stores it in object storage; apps/worker pulls it back out and dynamically
-- import()s it. api and worker are separate containers from separate images
-- that share no volume, so the code itself travels through S3 and this table
-- only carries its durable metadata plus the worker's local cache hints.
-- object_key is the private bucket key and MUST NEVER be returned to any
-- client: it is resolved server-side by the worker, clients only ever see
-- plugin_id / plugin_version / display_name.
-- ============================================================================
CREATE TABLE IF NOT EXISTS provider_plugins (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  plugin_id text NOT NULL,
  plugin_version text NOT NULL DEFAULT '1.0.0',
  kind text NOT NULL CHECK(kind IN ('media','language')),
  display_name text NOT NULL,
  description text,
  source text NOT NULL DEFAULT 'uploaded' CHECK(source IN ('builtin','uploaded')),
  status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','active','disabled','failed')),
  object_key text NOT NULL,
  artifact_sha256 text NOT NULL,
  artifact_size_bytes integer NOT NULL CHECK(artifact_size_bytes > 0),
  manifest jsonb NOT NULL,
  allowed_hosts jsonb NOT NULL DEFAULT '[]',
  credential_schemas jsonb NOT NULL DEFAULT '[]',
  scan_report jsonb NOT NULL DEFAULT '[]',
  error_code text,
  error_message text,
  installed_by uuid REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  UNIQUE(plugin_id, plugin_version)
);
-- Worker refresh query: usable packages for one kind (kind, status='active').
CREATE INDEX IF NOT EXISTS provider_plugins_kind_status_idx ON provider_plugins(kind, status) WHERE deleted_at IS NULL;
-- Artifact dedupe / integrity lookups by checksum.
CREATE INDEX IF NOT EXISTS provider_plugins_sha256_idx ON provider_plugins(artifact_sha256);
-- Incremental watermark refresh: "anything with updated_at after the last seen
-- high-water mark", so the worker never rescans the whole table.
CREATE INDEX IF NOT EXISTS provider_plugins_updated_at_idx ON provider_plugins(updated_at);

-- Which resolution path a model's plugin takes: 'builtin' ships in
-- packages/providers, 'installed' is served from a provider_plugins artifact.
ALTER TABLE model_configs ADD COLUMN IF NOT EXISTS plugin_source text NOT NULL DEFAULT 'builtin';
DO $$ BEGIN ALTER TABLE model_configs ADD CONSTRAINT model_configs_plugin_source_check CHECK(plugin_source IN ('builtin','installed')); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
