-- asset_thumbnails
-- Extracted verbatim from the historical packages/database/src/migrate.ts statement
-- stream (statements 221..229). Do not edit this file once it has been applied
-- anywhere: retiring schema requires a new migration containing the DROP.
--
-- Derived preview columns, then the asset_deletion_active_key rebuild (drop and recreate stay in one transaction).


-- Do NOT add another model_configs.plugin_id backfill here. The pre-existing
-- UPDATE above already stamps plugin_id onto EVERY row (language rows get
-- 'openai-language'/'anthropic-language', video '-video', image '-image'), and
-- none of those ids is registered anywhere. A non-null plugin_id therefore does
-- NOT mean "this model is bound to an installed plugin": consumers must gate on
-- actual registry/catalog membership (globalPluginRegistry.kindOf(...) or a
-- provider_plugins lookup), never on the column merely being non-null.

-- 12. Derived preview objects (worker-generated gallery thumbnails).
-- The library grid used to point every tile at the ORIGINAL object_key, so one
-- screen of 50 tiles downloaded 50 full-resolution images, and video tiles had
-- no poster at all (poster_object_key had readers but no writer) and each one
-- made the browser fetch video header bytes just to paint frame zero.
--
-- thumbnail_state is what makes backfill convergent: 'none' means "never
-- attempted", 'failed' means "attempted and could not be derived", so a
-- re-runnable sweep can select ('none','failed') and still terminate instead of
-- retrying a permanently unusable object forever.
ALTER TABLE assets ADD COLUMN IF NOT EXISTS thumbnail_object_key text;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS thumbnail_mime_type text;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS thumbnail_width integer;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS thumbnail_height integer;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS thumbnail_state text NOT NULL DEFAULT 'none';
DO $$ BEGIN ALTER TABLE assets ADD CONSTRAINT assets_thumbnail_state_check CHECK(thumbnail_state IN ('none','ready','failed')); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
-- Backfill / maintenance scan: rows still missing a derived object.
CREATE INDEX IF NOT EXISTS assets_thumbnail_missing_idx ON assets(created_at) WHERE deleted_at IS NULL AND thumbnail_object_key IS NULL;

-- One asset can now own more than one object (original + derived preview; video
-- points poster_object_key and thumbnail_object_key at the SAME derived object).
-- asset_deletion_active_key was UNIQUE(asset_id) WHERE completed_at IS NULL, and
-- deletion enqueues one row per object_key with ON CONFLICT DO NOTHING, so every
-- second object of an asset was silently swallowed and leaked in the bucket
-- (pre-existing bug: it already applied to poster_object_key). Widening the key
-- to (asset_id, object_key) keeps the per-object dedupe while letting the
-- pending rows drain. Rebuilt in this same section so a partially migrated
-- database never has neither index.
DROP INDEX IF EXISTS asset_deletion_active_key;
CREATE UNIQUE INDEX IF NOT EXISTS asset_deletion_active_key ON asset_deletion_jobs(asset_id, object_key) WHERE completed_at IS NULL;
