import { randomBytes } from 'node:crypto'
import { appendFileSync, existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const hex = (bytes) => randomBytes(bytes).toString('hex')

const envPath = resolve(dirname(fileURLToPath(import.meta.url)), '..', '.env')

// Bootstrap-only secrets. SMTP, S3 app config, public origin, OAuth settings,
// limits, and prompt templates are database settings managed via the
// onboarding wizard at /setup — never generate them here.
const BOOTSTRAP_KEYS = [
  { key: 'POSTGRES_PASSWORD', value: () => hex(24) },
  // Exactly 32 bytes, hex-encoded (64 chars). See packages/config for the
  // accepted APP_MASTER_KEY encodings (64 hex chars or base64/base64url).
  { key: 'APP_MASTER_KEY', value: () => hex(32) },
  { key: 'MINIO_ROOT_USER', value: () => 'musecanvas' },
  { key: 'MINIO_ROOT_PASSWORD', value: () => hex(24) },
]

const hasKey = (content, key) => new RegExp(`^${key}=`, 'm').test(content)

if (!existsSync(envPath)) {
  const env = [
    '# Auto-generated by scripts/generate-env.mjs — edit values in place; delete to regenerate.',
    '# Bootstrap secrets only: Postgres + bundled MinIO + application master key.',
    '# SMTP, S3 app config, public origin, OAuth, limits, and prompt templates',
    '# are database settings configured via the onboarding wizard at /setup.',
    ...BOOTSTRAP_KEYS.map(({ key, value }) => `${key}=${value()}`),
    '',
  ].join('\n')
  writeFileSync(envPath, env, 'utf-8')
  console.log('Generated .env with bootstrap secrets (POSTGRES_PASSWORD, APP_MASTER_KEY, MINIO_ROOT_*)')
  process.exit(0)
}

// Upgrade path: append only missing bootstrap keys; never change existing
// values.
const content = readFileSync(envPath, 'utf-8')
const missing = BOOTSTRAP_KEYS.filter(({ key }) => !hasKey(content, key))
if (missing.length === 0) {
  console.log('.env already has all bootstrap keys, nothing to do')
  process.exit(0)
}
const prefix = content.endsWith('\n') ? '' : '\n'
const block =
  `${prefix}# Added by scripts/generate-env.mjs upgrade — new bootstrap keys (existing values untouched)\n` +
  missing.map(({ key, value }) => `${key}=${value()}`).join('\n') +
  '\n'
appendFileSync(envPath, block, 'utf-8')
console.log(`Appended missing bootstrap keys to .env: ${missing.map(({ key }) => key).join(', ')}`)
