import { randomBytes } from 'node:crypto'
import { existsSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const hex = (bytes) => randomBytes(bytes).toString('hex')

const envPath = resolve(dirname(fileURLToPath(import.meta.url)), '..', '.env')

if (existsSync(envPath)) {
  console.log('.env already exists, skipping generation')
  process.exit(0)
}

const env = [
  '# Auto-generated by scripts/generate-env.mjs — edit or delete to regenerate',
  `POSTGRES_PASSWORD=${hex(24)}`,
  `SESSION_SECRET=${hex(32)}`,
  `S3_ACCESS_KEY_ID=${hex(12)}`,
  `S3_SECRET_ACCESS_KEY=${hex(28)}`,
  `OAUTH_CREDENTIALS_ENCRYPTION_KEY=${hex(32)}`,
  `PROVIDER_CREDENTIALS_ENCRYPTION_KEY=${hex(32)}`,
  'PROMPT_TEMPLATE_INDEX_PATH=./Template/index.json',
  '',
  '# Admin email is set via the onboarding wizard at /setup on first launch.',
  '# SMTP defaults to Mailpit in dev (no configuration needed).',
  '# OAUTH_REDIRECT_BASE_URL defaults to http://localhost:8080.',
  '',
].join('\n')

writeFileSync(envPath, env, 'utf-8')
console.log('Generated .env with random secrets')